# Build container images according to https://github.com/marketplace/actions/build-and-push-docker-images
name: ci
on: [push, pull_request]
#on:
#  push:
#    branches:
#      - 'master'

jobs:
  matrix:
    # Generate matrix for linting (essentially locating all Dockerfile directories)
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-dockerfiles.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2 
    - id: set-dockerfiles
      run: |
        pwd
        ls
        chmod +x paths_to_dockerfile.sh
        ./paths_to_dockerfile.sh | jq .
        PATHS_TO_DOCKERFILE=`./paths_to_dockerfile.sh | jq .`
        echo "::set-output name=matrix::$PATHS_TO_DOCKERFILE"
  linter:
    # Run linter on all located Dockerfiles
    needs: [matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ${{ matrix.dockerfiles }}
  build:
    needs: [linter]
    # Should consider to use https://github.com/marketplace/actions/build-and-push-docker-images instead, but requires rewrite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
#      - name: Run build script
#        run: ./build.sh
